version: '3'
services:
  db:
    image: postgres:9.6
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - kamuskita-db:/var/lib/postgresql/data

  web:
    build: .
    command: bundle exec rails s -e production -p 3000 -b '0.0.0.0'
    links:
      - db
    volumes:
      - .:/kamuskita
    ports:
      - '8000:3000'
    env_file:
      - .env

volumes:
  kamuskita-db: {}