default: &default
  adapter: postgresql
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  host: localhost
  database: kamus_kita_development
  
test:
  <<: *default
  database: kamus_kita_test

production:
  <<: *default
  host: <%= ENV["POSTGRES_HOST"] %>
  database: <%= ENV["POSTGRES_DB"] %>
  port: <%= ENV["POSTGRES_PORT"] %>
